# Dumb ci job to experiment with more consise matrices, than fully explicit include only.
name: matrix-testing

# Run on branch push events (i.e. not tag pushes) and on pull requests
on:
  push:
    branches:
      - '**'
    paths:
      - "**"
      - "!.github/**"
      - ".github/workflows/matrix-testing.yml"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.compilers.os }}
    # container:
    #   image: quay.io/pypa/manylinux2014_x86_64
    strategy:
      fail-fast: false

      # Matrix needs to specify: 
      # + OS?
      # + Container?
      # + CUDA version + cuda_arch as a pair, + host compiler (gcc / msvc version.)
      # + python version
      # + If vis is on/off. This might require explicit include? 
      # + Build config and SEATBELTS.


      matrix:
        compilers:
          - name: "CUDA 11.4"
            cuda: "11.4"
            cuda_arch: "52 60"
            cxx: gcc-9
            os: ubuntu-20.04
          # - name: "CUDA 11.0"
          #   cuda: "11.0"
          #   cuda_arch: "52 60"
          #   cxx: gcc-8
          #   os: ubuntu-20.04
          - name: "CUDA 10.0"
            cuda: "10.0"
            cuda_arch: "35"
            cxx: gcc-7
            os: ubuntu-18.04
        config:
          - name: Fast
            SEATBELTS: "OFF"
            config: "Release"
          - name: Slow
            SEATBELTS: "ON"
            CONFIG: "Release"
          # - name: Debug
          #   SEATBELTS: "ON"
          #   config: Debug
        python: [3.6, 3.7]
        VISUALISATION: ["ON", "OFF"]

    # Explicitly define env bits, AND promote matrix components to the env, for more portable steps between jobs.
    env:
      BUILD_DIR: "build"
      BUILD_TESTS: "OFF"
      BUILD_SWIG_PYTHON: "ON"

      VISUALISATION: ${{ matrix.VISUALISATION }}
      compilers: ${{ matrix.compilers }}
      config: ${{ matrix.config }}
      python: ${{ matrix.python }}

    # Name the build based on matrix/env options (but simplified?)
    name: build (${{ matrix.compilers.name }} ${{ matrix.config.name }} ${{matrix.python}} ${{ matrix.VISUALISATION}})

    steps:
    - uses: actions/checkout@v2

   
    - name: Output Matrix.
      shell: bash
      run: |
        echo "${{ toJSON(matrix) }}"

    - name: Output Matrix.
      shell: bash
      run: |
        echo "${{ toJSON(env) }}"
        


