# Dumb ci job to experiment with more consise matrices, than fully explicit include only.
name: matrix-testing

# Run on branch push events (i.e. not tag pushes) and on pull requests
on:
  push:
    branches:
      - '**'
    paths:
      - "**"
      - "!.github/**"
      - ".github/workflows/matrix-testing.yml"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  public:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Output event.
      shell: bash
      run: |
        echo "${{ toJSON(github.event) }}"

  draft:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Output event.
      shell: bash
      run: |
        echo "${{ toJSON(github.event) }}"

  always:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Output event.
      shell: bash
      run: |
        echo "${{ toJSON(github.event) }}"