# Dumb ci job to experiment with more consise matrices, than fully explicit include only.
name: matrix-testing

# Run on branch push events (i.e. not tag pushes) and on pull requests
on:
  push:
    branches:
      - '**'
    paths:
      - "**"
      - "!.github/**"
      - ".github/workflows/matrix-testing.yml"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    # container:
    #   image: quay.io/pypa/manylinux2014_x86_64
    strategy:
      fail-fast: false

      # Matrix needs to specify: 
      # + OS?
      # + Container?
      # + CUDA version + cuda_arch as a pair, + host compiler (gcc / msvc version.)
      # + python version
      # + If vis is on/off. This might require explicit include? 
      # + Build config and SEATBELTS.


      matrix:
        compilers:
          - name: "CUDA 11.4"
            cuda: "11.4"
            cuda_arch: "52 60"
            cxx: gcc-9
          - name: "CUDA 11.0"
            cuda: "11.0"
            cuda_arch: "52 60"
            cxx: gcc-8
          - name: "CUDA 10.0"
            cuda: "10.0"
            cuda_arch: "35"
            cxx: gcc-7
            os: ubuntu-18.04
        configs:
          - name: Fast
            SEATBELTS: "OFF"
            config: "Release"
          - name: Slow
            SEATBELTS: "ON"
            config: "Release"
          - name: Debug
            SEATBELTS: "ON"
            config: Debug
        python: [3.6, 3.7]
        VISUALISATION: ["ON", "OFF"]


        


    env:
      BUILD_DIR: "build"
      CONFIG: "Release"
      BUILD_TESTS: "OFF"
      BUILD_SWIG_PYTHON: "ON"
      VISUALISATION: "OFF"

    steps:
    - uses: actions/checkout@v2

   
    - name: Output Information.
      shell: bash
      run: |
        echo "${{ toJSON(matrix) }}"
        


